### ISSUE TITLE
Fix Schema for Hubspot

### ISSUE THREAD

**Issue by dyaffe** [estuary/airbyte#109]
**Problem**
Hubspot has four collections that which have an array field that can be a `string`, `integer` or `null`:

The field is: `contacts`

The collections are:
`engagement_emails`
`engagement_notes`
`engagement_tasks`
`engagement_meetings`

**Comment by dyaffe** [comment]
@mdibaiee I'm seeing this in production.  I'm also seeing a new one

The `contacts` collection has a field called `contacts` that is an array of `null` or `string` values.  They apparently can also be integers.  

This is one that maybe we should auto-convert to a string?  It seems like a data issue.

**Comment by mdibaiee** [comment]
@dyaffe when these values are `string`, are they actually a number but presented as a string, or are they non-numeric string values?

We currently support auto-converting strings that are numbers to numbers, but not the other way around.

**Comment by dyaffe** [comment]
the collection `companies` has a field called `contacts` and the collection `contacts` has a field called `companies`

Both have `integer` values that can either be represented as `integer` or `string`.
