### ISSUE TITLE
Fix Schema for SurveyMonkey

### ISSUE THREAD

**Issue by dyaffe** [estuary/airbyte#121]
**Problem**
Survey Monkey has a collection called `survey_questions`.  It has a field called `validation` which has a `min` and `max`.  Both of which can be `string` values formatted as `integer`, `null` or `integers`.  We should update it in `airbyte_to_flow` like this:

```
        "max": {
            "type": [
              "integer",
              "null"
            ]
          },
          "min": {
            "type": [
              "integer",
              "null"
            ]
          },
```
i think if they were this instead that error would be solved:
  ```
        "max": {
            "type": [
              "integer",
              "null",
              "string"
            ],
            "format": "integer"
          },
          "min": {
            "type": [
              "integer",
              "null",
              "string"
            ],
            "format": "integer"
          },
```

**Comment by jman0119** [comment]
PR 122 completed to fix this issue: https://github.com/estuary/airbyte/pull/122
