### ISSUE TITLE
Update airbyte for Mailchimp

### ISSUE THREAD

**Issue by esty-scott** [estuary/airbyte#144]
Getting errors trying to capture Mailchimp data, even though my Test of the capture succeeded. This is for Barnett/Mailchimp capture.

runTransactions: app.ConsumeMessage: combiner.Drain: document failed validation against its collection JSON Schema

Caused by:
    {
      "basic_output": {
        "errors": [
          {
            "absoluteKeywordLocation": "file:///flow.json?ptr=/collections/Barnett~1Mailchimp~1campaigns/schema#/properties/type",
            "error": "Invalid: Must be one of ""regular"", "plaintext"", "absplit"", "rss"", "variate"".",
            "instanceLocation": "/type",
            "keywordLocation": "#/properties/type"
          }
        ],
        "valid": false
      },
      "document": {
        "_links": [
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns",
            "method": "GET",
            "rel": "parent",
            "schema": "https://us5.api.mailchimp.com/schema/3.0/Paths/Campaigns/Collection.json",
            "targetSchema": "https://us5.api.mailchimp.com/schema/3.0/Definitions/Campaigns/CollectionResponse.json"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53",
            "method": "GET",
            "rel": "self",
            "targetSchema": "https://us5.api.mailchimp.com/schema/3.0/Definitions/Campaigns/Response.json"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53",
            "method": "DELETE",
            "rel": "delete"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/actions/send",
            "method": "POST",
            "rel": "send"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/actions/cancel-send",
            "method": "POST",
            "rel": "cancel_send"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/feedback",
            "method": "GET",
            "rel": "feedback",
            "targetSchema": "https://us5.api.mailchimp.com/schema/3.0/Definitions/Campaigns/Feedback/CollectionResponse.json"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/content",
            "method": "GET",
            "rel": "content",
            "targetSchema": "https://us5.api.mailchimp.com/schema/3.0/Definitions/Campaigns/Content/Response.json"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/send-checklist",
            "method": "GET",
            "rel": "send_checklist",
            "targetSchema": "https://us5.api.mailchimp.com/schema/3.0/Definitions/Campaigns/Checklist/Response.json"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/actions/pause",
            "method": "POST",
            "rel": "pause"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/actions/resume",
            "method": "POST",
            "rel": "resume"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/actions/replicate",
            "method": "POST",
            "rel": "replicate"
          },
          {
            "href": "https://us5.api.mailchimp.com/3.0/campaigns/0df153fd53/actions/create-resend",
            "method": "POST",
            "rel": "create_resend"
          }
        ],
        "_meta": {
          "uuid": "DocUUIDPlaceholder-329Bb50aa48EAa9ef"
        },
        "archive_url": "http://eepurl.com/ii1Aiv",
        "content_type": "template",
        "create_time": "2023-01-23T19:19:45+00:00",
        "delivery_status": {
          "enabled": false
        },
        "emails_sent": 18,
        "id": "0df153fd53",
        "long_archive_url": "https://us5.campaign-archive.com/?u=cb3b8057a7f5b9c92e4fdd155&id=0df153fd53",
        "needs_block_refresh": false,
        "recipients": {
          "list_id": "1349117a18",
          "list_is_active": true,
          "list_name": "App Signups: Capture but no Materializations in > 24h",
          "recipient_count": 33,
          "segment_text": ""
        },
        "report_summary": {
          "click_rate": 0.05555555555555555,
          "clicks": 1,
          "ecommerce": {
            "total_orders": 0,
            "total_revenue": 0,
            "total_spent": 0
          },
          "open_rate": 0.6111111111111112,
          "opens": 23,
          "subscriber_clicks": 1,
          "unique_opens": 11
        },
        "resendable": false,
        "send_time": "2023-02-12T18:42:11+00:00",
        "settings": {
          "authenticate": true,
          "auto_footer": false,
          "auto_tweet": false,
          "drag_and_drop": true,
          "fb_comments": true,
          "folder_id": "",
          "from_name": "Estuary",
          "inline_css": false,
          "reply_to": "info@estuary.dev",
          "subject_line": "Email contacts",
          "template_id": 13682706,
          "timewarp": false,
          "title": "Email contacts from your customer journey",
          "to_name": "",
          "use_conversation": false
        },
        "status": "sending",
        "tracking": {
          "clicktale": "",
          "ecomm360": false,
          "goal_tracking": false,
          "google_analytics": "",
          "html_clicks": true,
          "opens": true,
          "text_clicks": false
        },
        "type": "automation-email",
        "web_id": 9288102
      }
    }

**Comment by dyaffe** [comment]
@mdibaiee Johnny suggested a fix here where we don't strictly apply enums.  Is that something we could do in airbyte-to-flow?
