### ISSUE TITLE
Primary Key Detection for Google Sheets Connector

### ISSUE THREAD

**Issue by dyaffe** [estuary/airbyte#6]
Problem:
There's currently no way for us to determine the primary key with the Google Sheets connector.  Usage of it through the UI is very clumsy since it's difficult to figure out and manually edit JSON.

Proposed Solution:
We should first search for any protected range that is always available.  If there aren't protected ranges that are available, we should use the row number as the primary key.

**Comment by mdibaiee** [comment]
@dyaffe what is the incentive behind checking for a "protected range", what does that even mean? (noob sheets question!)

**Comment by dyaffe** [comment]
A protected range is a way for a user to prevent others from editing the contents of a column -- usually that will infer that it's a primary key.  That said, this is a "nice to have" and if row numbers are easier, we should absolutely just limit this to that.

**Comment by mdibaiee** [comment]
row_id as primary key has been implemented here: https://github.com/estuary/airbyte/pull/10
