### ISSUE TITLE
Hubspot Connector Updates

### ISSUE THREAD

**Issue by dyaffe** [estuary/airbyte#7]
Problem:
Our Hubspot connector currently fails whenever someone doesn't have Hubspot pro.  This is because a set number of Hubspots streams are reserved for their pro account.

Proposed Solution:
Add a checkbox to the config which dictates whether the customer has pro or not.  When they don't have pro, we remove the streams that require pro automatically.  This should default to "Not Pro" to prevent issues.

**Comment by mdibaiee** [comment]
Fixed here: https://github.com/estuary/airbyte/pull/9
